apiVersion: v1
kind: Service
metadata:
    name: "aksanegru-1173"
    labels:
        app: "aksanegru-1173"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksanegru-1173"